### ISSUE TITLE
Remove hubot-shipit

### ISSUE THREAD

**Issue by jonfairbanks** [bsord/sonny#3]
Per multiple sources, bots and/or commands that pollute the channel or answer un-necessarily are bad Slack etiquette.

- https://hiverhq.com/blog/slack-etiquette
- https://slatiquette.com/

Although you are not the owner of hubot-shipit, please consider removing it as a dependency here because of this reason.

**Comment by jonfairbanks** [comment]
Opened https://github.com/bsord/sonny/pull/4 to resolve.

**Comment by bsord** [comment]
Merged and resolved.
